name: 'taichunmin auto-renew-1: fUSD'

on:
  workflow_dispatch:
  schedule:
    # timezone: UTC
    # 避開整點時間，因為有可能會有時間上的延誤
    - cron: '6-56/10 * * * *'

jobs:
  bitfinex:
    # 避免被 fork 的 repository 觸發，請改成自己的 GitHub 帳號
    if: github.repository_owner == 'taichunmin'
    # 這個名字必須跟 repo 的 Environments 名稱一樣
    environment: taichunmin-usd-1
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dump GitHub Context
        run: |
          echo 'env=${{ toJSON(env) }}'
          echo 'github=${{ toJSON(github) }}'
          echo 'inputs=${{ toJSON(inputs) }}'
          echo 'job=${{ toJSON(job) }}'
          echo 'runner=${{ toJSON(runner) }}'
          echo 'secrets=${{ toJSON(secrets) }}'
          echo 'steps=${{ toJSON(steps) }}'
          echo 'vars=${{ toJSON(vars) }}'
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies, eslint, and run
        env:
          BITFINEX_API_KEY: ${{ secrets.BITFINEX_API_KEY }}
          BITFINEX_API_SECRET: ${{ secrets.BITFINEX_API_SECRET }}
          INPUT_AMOUNT: 0
          INPUT_CURRENCY: USD
          INPUT_PERIOD: 2
          INPUT_RATE_MIN: 0.0002
          INPUT_RATE_MAX: 0.01
        run: |
          set -ex
          yarn
          yarn lint
          node ./bin/funding-auto-renew-1.mjs
